### ISSUE TITLE
problem of "call_preprocessing"

### ISSUE THREAD

**Issue by Wusir2018** [nilmtk/nilmtk-contrib#39]
Hello everyone,
I have some question about "call_preprocessing" in all deep learning methods.
1. The `call_preprocessing` of methods to process the data, but why fill in the `mains` data and `appliance` data? Could you give me the paper that uses this method to process data?

```
new_mains = np.pad(new_mains,(units_to_pad,units_to_pad),'constant',constant_values=(0,0))
new_mains = np.array([new_mains[i:i + n] for i in range(len(new_mains) - n + 1)])
```

```
new_app_readings = np.pad(new_app_readings,(units_to_pad,units_to_pad),'constant',constant_values = (0,0))
new_app_readings = np.array([new_app_readings[i:i + n] for i in range(len(new_app_readings) - n + 1)])  
```

2. What is the reason for setting value of `sequence_length`，`mains_mean` and `mains_std`?  Why set `sequence_length` to 19 in `RNN` and `sequence_length` to 99 in `Seq2Seq and Seq2Point`?

3. Why set `mains_mean` to 1800 and `mains_std` to 600 in all methods?

Could you help me? Thank you very much!
Best wishes!

**Comment by levaphenyl** [comment]
### Question 1
Padding is due to the very nature of window-based algorithms. For instance, for Seq2Point, the algorithms takes a window (array) as an input and outputs a single value. Thus, you need a window *for each point to infer*.
In
`new_mains = np.pad(new_mains,(units_to_pad,units_to_pad),'constant',constant_values=(0,0))`
the method is given an array of lenght *L* to infer another array of the same length. How to infer the first and the last point, then?
Solution: you pad before and after the input array to make it of length *L + 2 * n*, *n* being the window size.

Second, you need to feed the input array window by window in the neural net.
The line
`new_mains = np.array([new_mains[i:i + n] for i in range(len(new_mains) - n + 1)])`
prepares each window from the input data.

[Paper of NILMTK-contrib](https://dl.acm.org/doi/10.1145/3360322.3360844)

### Questions 2 & 3
Those are default values and you are free to change them. Why those values, I don't know.

**Comment by Wusir2018** [comment]
@levaphenyl 
Thank you very much! 👍 
Best wishes!

**Comment by Rithwikksvr** [comment]
Yes, @levaphenyl  is right

Those are default values, no specific reason as to why we chose them
